logo : /assets/Screenshot 2025-02-13 204548.png
title: Resume & Portfolio
email: dusaondrej@gmail.com
description: Senior year Data Analytics Major | President of Data Analytics Student Association | Division 1 Swimmer | Queens Univeristy of Charlotte
favicon: true
#color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ondrej-dusa
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/ondrej-dusa-10955b21a/

navigation:
  - name: Resume
    link: https://ondrej-dusa.github.io/Portfolio/
  - name: Projects
    link: https://ondrej-dusa.github.io/Portfolio/Projects.html
    sublist:
      - name: Two-Year Expense Analysis and Forecasting Project
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Two-Year%20Expense%20Analysis%20and%20Forecasting%20Project.html
      - name: Risk Analysis (VaR)
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Risk%20Analysis%20and%20Value%20at%20Risk%20(VaR).html
      - name: Coffee Sales 2024
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Coffee%20Sales%202024.html
      - name: EDA of MPG
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Exploratory%20Data%20Analysis%20(EDA)%20of%20MPG%20Dataset.html
        
#theme: jekyll-theme-minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
