title: Portfolio
logo : /assets/Screenshot 2025-02-13 204548.png
author: Ondrej Dusa
description: My personal portfolio of my Data Minning, Science and Analytics work.
show_downloads: true
theme: jekyll-theme-minimal

[Projects](./Projects.md)
