title: Portfolio
logo : /assets/LinkedIN.jpg
author: Ondrej Dusa
description: My personal portfolio of my Data Minning, Science and Analytics work.
show_download: true
theme: jekyll-theme-minimal
