logo : /assets/Screenshot 2025-02-13 204548.png
title: Resume & Portfolio
email: dusaondrej@gmail.com
description: Senior year Data Analytics Major | President of Data Analytics Student Association | Division 1 Swimmer | Queens Univeristy of Charlotte
favicon: true
#color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ondrej-dusa
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/ondrejdusa/

navigation:
  - name: Resume
    link: https://ondrej-dusa.github.io/Portfolio/
  - name: Websites
    link: https://ondrej-dusa.github.io/Portfolio/Websites.html
  - name: Projects
    link: https://ondrej-dusa.github.io/Portfolio/Projects.html
    sublist:
      - name: E-commerce Sales Analysis
        link: https://ondrej-dusa.github.io/Portfolio/Projects/E-commerce%20Sales%20Analysis.html
      - name: Email Classification
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Email%20Classification%20Using%20Multinomial%20Naive%20Bayes.html
      - name: Risk Analysis (VaR)
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Risk%20Analysis%20and%20Value%20at%20Risk%20(VaR).html
      - name: EDA of MPG
        link: https://ondrej-dusa.github.io/Portfolio/Projects/Exploratory%20Data%20Analysis%20(EDA)%20of%20MPG%20Dataset.html
        
#theme: jekyll-theme-minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
